<?php

    function primeSifting($limit) {
        $numbers = range(2, $limit);
        $numbers = array_combine($numbers, $numbers);
        foreach ($numbers as $number) {
            $x = $number;
            while($x<$limit) {
                $x += $number;
                unset($numbers[$x]);
            }
        }
        return sizeof($numbers);
    }

    function prime_sifting_menu() {
        $items['prime_sifting'] = array(
            'title' => 'Prime Number',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('prime_sifting_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['prime_results'] = array(
            'title' => 'Prime Results',
            'page callback' => 'prime_results',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function prime_sifting_form() {
        $form['number'] = array(
            '#title' => 'Input',
            '#type' => 'textfield',
            '#description' => 'Enter your maximum number to find primes',
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Calculate',
        );
        return $form;
    }

    function prime_sifting_form_submit($form, &$form_state) {
        $_SESSION['prime_input'] = $form_state['values']['number'];

        $form_state['redirect'] = 'prime_results';
    }

    function prime_results() {
        $input = $_SESSION['prime_input'];
        $number_primes = primeSifting($input);
        return "There are $number_primes prime numbers between 0 and $input.";
    }

 ?>
